matrix:
  include:
    - os: linux
      dist: focal
      #dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode13.1

addons:
  apt:
#    sources:
#      - sourceline: 'ppa:beineri/opt-qt591-trusty'
    packages:
      #- qt59base
      - libsqlite3-dev
      - libmysqlclient-dev
      #- libssl1.0.0
      - libssl-dev
      - qt5-default

before_install:
  - ./ci/travis/before_install_${TRAVIS_OS_NAME}.sh

script:
  # Add installed Qt path to $PATH
  # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt*/bin/qt*-env.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source qt-5.env; fi
  # Build and install
  - qmake -r
  - make -j2
  #- make INSTALL_ROOT=appdir install
  # Set VERSION env var
  #- export VERSION=$(./get_version.sh)
  # Package deployment artifacts
  #- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./make_dist_linux.sh "maven/appdir/bin/maven_dev_${VERSION}"; fi
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./make_dist_osx.sh "maven/appdir/bin/Maven.app"; fi
  #- ls -la dist/
